name: app
description: SparX Wallet Flutter app
version: 1.2.1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  app_settings: 5.1.1
  auto_size_text_field: 2.2.4
  barcode_widget: 2.0.4
  bloc: 8.1.4
  broxus_app_links:
    git:
      url: https://github.com/broxus/broxus-flutter-app-link
      ref: v1.0.0
  cached_network_image: 3.4.1
  cached_network_svg_image: 1.2.0
  clock: 1.1.1
  collection: 1.18.0
  crypto: 3.0.6
  device_info_plus: 11.2.1
  dio: 5.7.0
  easy_localization: 3.0.7
  easy_logger: 0.0.2
  elementary: 3.2.0
  elementary_helper: 1.0.2
  encrypted_storage: 0.1.3
  equatable: 2.0.7
  event_bus: 2.0.1
  favicon: 1.1.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_email_sender: 6.0.3
  flutter_inappwebview: 6.1.5
  flutter_screenutil: 5.9.3
  flutter_secure_storage: 9.2.4
  flutter_svg: 2.0.17
  freezed_annotation: 2.4.4
  get_it: 8.0.3
  get_storage: 2.1.1
  go_router: 14.6.3
  http: 1.2.2
  image_picker: 1.1.2
  in_app_notification: 1.1.2
  injectable: 2.5.0
  internet_connection_checker_plus: 2.7.0
  jdenticon_dart: 2.0.0
  json_annotation: 4.9.0
  local_auth: 2.3.0
  logging: 1.3.0
  lucide_icons_flutter: 1.2.5
  mobile_scanner: 5.2.3
  money2: 5.3.0 # do not update to 5.4.0 due to json serialization issues
  money2_fixer: 2.0.0
  nekoton_repository: 0.51.0-dev.2
  nekoton_webview: 0.1.8
  ntp: 2.0.0
  package_info_plus: 8.1.3
  path_provider: 2.1.5
  permission_handler: 11.3.1
  render_metrics:
    #    Temporarily. Before the adoption of the PR
    #    https://github:com/surfstudio/flutter-render-metrics/pull/27:
    git:
      url: https://github.com/knightsforce/flutter-render-metrics
      ref: optional-render-manager
  retrofit: 4.4.2
  rxdart: 0.27.7
  sentry_flutter: 8.12.0
  share_plus: 10.1.4
  shared_preferences: 2.3.5
  string_extensions: 0.7.3
  the_logger: 0.0.17
  ui_components_lib:
    path: packages/ui_components_lib
  url_launcher: 6.3.1
  uuid: 4.5.1
  visibility_detector: 0.4.0+2

dev_dependencies:
  bloc_test: 9.1.7
  broxus_flutter_analysis:
    git:
      url: https://github.com/broxus/flutter_templates.git
      ref: main
  build_runner: 2.4.13
  custom_lint: 0.5.11
  datetime_avoid_lint:
    path: packages/datetime_avoid_lint
  flutter_gen_runner: 5.8.0
  flutter_native_splash: 2.4.4
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  googleapis_auth: 1.6.0
  injectable_generator: 2.6.2
  integration_test:
    sdk: flutter
  intl: 0.19.0
  json_serializable: 6.9.0
  melos: 6.3.1
  mocktail: 1.0.4
  retrofit_generator: 9.1.5
  test: 1.25.7

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/abi/
    - assets/configs/
    - assets/images/
    - assets/images/onboarding/layer1/
    - assets/images/onboarding/layer2/
    - assets/images/onboarding/layer3/
    - assets/images/onboarding/
    - assets/images/lang_icons/
    - assets/images/stever/
    - assets/images/user_avatar/
    - assets/images/alert_octagon_fill/
    - assets/images/check_circle_fill/
    - assets/images/wallet_bg/
    - assets/splash/
    - assets/js/
